---
title: "PA 5"
author: "Chau Nguyen"
date: "2/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## R Markdown

```{r four times seven}
times_seven <- function(x){
  stopifnot(is.numeric(x))
  
  if(x == 7){
    print("I love sevens!")
  }
  return(x*7)
}


```


```{r add or subtract}
add_or_subtract <- function(first_num, 
                            second_num = 2, 
                            type = "add") {
  
  if (type == "add") {
    first_num + second_num
  } else if (type == "subtract") {
    first_num - second_num
  } else {
    stop("Please choose `add` or `subtract` as the type.")
  }
  
}
```

## Including Plots

You can also embed plots, for example:

```{r question2}

add_or_subtract(5, 6, type = "subtract")

add_or_subtract("orange")

add_or_subtract(5, 6, type = "multiply")
```
```{r global}

first_num <- 5
second_num <- 3

result <- 8

result <- add_or_subtract(first_num, second_num = 4)

result_2 <- add_or_subtract(first_num)

```

